// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: tensorvault/v1/tensorvault.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 消息定义 ---
// [新增] 检查文件请求
type CheckFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件的全量线性 SHA-256 哈希 (用于查找秒传索引)
	Sha256 string `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// 文件大小 (字节)，用于辅助校验
	Size          int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFileRequest) Reset() {
	*x = CheckFileRequest{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFileRequest) ProtoMessage() {}

func (x *CheckFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFileRequest.ProtoReflect.Descriptor instead.
func (*CheckFileRequest) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{0}
}

func (x *CheckFileRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *CheckFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// [新增] 检查文件响应
type CheckFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否已存在 (如果为 true，客户端可以跳过上传)
	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// 如果存在，直接返回对应的 Merkle Root Hash (FileNode ID)
	// 只有当 exists=true 时，此字段才有值
	MerkleRootHash *string `protobuf:"bytes,2,opt,name=merkle_root_hash,json=merkleRootHash,proto3,oneof" json:"merkle_root_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckFileResponse) Reset() {
	*x = CheckFileResponse{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFileResponse) ProtoMessage() {}

func (x *CheckFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFileResponse.ProtoReflect.Descriptor instead.
func (*CheckFileResponse) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{1}
}

func (x *CheckFileResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckFileResponse) GetMerkleRootHash() string {
	if x != nil && x.MerkleRootHash != nil {
		return *x.MerkleRootHash
	}
	return ""
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oneof 是一种联合类型，意味着一次请求要么传元数据，要么传二进制
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadRequest_Meta
	//	*UploadRequest_ChunkData
	Payload       isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRequest) GetPayload() isUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadRequest) GetMeta() *FileMeta {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type UploadRequest_Meta struct {
	Meta *FileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"` // 第一次发送：文件名、大小等
}

type UploadRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"` // 后续发送：二进制块
}

func (*UploadRequest_Meta) isUploadRequest_Payload() {}

func (*UploadRequest_ChunkData) isUploadRequest_Payload() {}

type FileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// [新增] 客户端计算好的线性 SHA-256 哈希
	// 服务端必须在接收流的过程中重新计算，并在最后进行比对校验
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{3}
}

func (x *FileMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMeta) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // 最终生成的 Merkle Root
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{4}
}

func (x *UploadResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UploadResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // 要下载的文件/对象的 Hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"` // 二进制流片段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type GetHeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadRequest) Reset() {
	*x = GetHeadRequest{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadRequest) ProtoMessage() {}

func (x *GetHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadRequest.ProtoReflect.Descriptor instead.
func (*GetHeadRequest) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{7}
}

type GetHeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 用于乐观锁
	Exists        bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadResponse) Reset() {
	*x = GetHeadResponse{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadResponse) ProtoMessage() {}

func (x *GetHeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadResponse.ProtoReflect.Descriptor instead.
func (*GetHeadResponse) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{8}
}

func (x *GetHeadResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetHeadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetHeadResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1. 基础元数据
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Author  string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"` // 未来可能从 Auth Token 中提取，但目前保留
	// 2. [新增] 核心数据指针 (Payload)
	// 客户端必须先计算出当前的目录树 Hash，告诉服务端："这是我现在的项目快照"
	TreeHash string `protobuf:"bytes,3,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	// 3. [新增] 历史关系 (History)
	// 明确指出这个 Commit 的父节点是谁。
	// 通常是客户端读取到的当前 HEAD。如果不传，服务端可能默认基于当前 HEAD（但会有并发风险）。
	ParentHashes []string `protobuf:"bytes,4,rep,name=parent_hashes,json=parentHashes,proto3" json:"parent_hashes,omitempty"`
	// 4. [新增] 引用目标 (Reference)
	// 你要更新哪个分支？默认可能是 "HEAD" 或 "refs/heads/main"
	BranchName    string `protobuf:"bytes,5,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{9}
}

func (x *CommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CommitRequest) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

func (x *CommitRequest) GetParentHashes() []string {
	if x != nil {
		return x.ParentHashes
	}
	return nil
}

func (x *CommitRequest) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tensorvault_v1_tensorvault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_tensorvault_v1_tensorvault_proto_rawDescGZIP(), []int{10}
}

func (x *CommitResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

var File_tensorvault_v1_tensorvault_proto protoreflect.FileDescriptor

const file_tensorvault_v1_tensorvault_proto_rawDesc = "" +
	"\n" +
	" tensorvault/v1/tensorvault.proto\x12\x0etensorvault.v1\x1a\x1bbuf/validate/validate.proto\"a\n" +
	"\x10CheckFileRequest\x120\n" +
	"\x06sha256\x18\x01 \x01(\tB\x18\xbaH\x15r\x132\x0e^[a-fA-F0-9]+$\x98\x01@R\x06sha256\x12\x1b\n" +
	"\x04size\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x04size\"\x89\x01\n" +
	"\x11CheckFileResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12G\n" +
	"\x10merkle_root_hash\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x0e^[a-fA-F0-9]+$\x98\x01@H\x00R\x0emerkleRootHash\x88\x01\x01B\x13\n" +
	"\x11_merkle_root_hash\"k\n" +
	"\rUploadRequest\x12.\n" +
	"\x04meta\x18\x01 \x01(\v2\x18.tensorvault.v1.FileMetaH\x00R\x04meta\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"P\n" +
	"\bFileMeta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x120\n" +
	"\x06sha256\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x0e^[a-fA-F0-9]+$\x98\x01@R\x06sha256\"M\n" +
	"\x0eUploadResponse\x12\x1c\n" +
	"\x04hash\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\x04hash\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\"@\n" +
	"\x0fDownloadRequest\x12-\n" +
	"\x04hash\x18\x01 \x01(\tB\x19\xbaH\x16r\x14\x10\x04\x18@2\x0e^[a-fA-F0-9]+$R\x04hash\"1\n" +
	"\x10DownloadResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\"\x10\n" +
	"\x0eGetHeadRequest\"a\n" +
	"\x0fGetHeadResponse\x12\x1c\n" +
	"\x04hash\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\x04hash\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\"\xc6\x01\n" +
	"\rCommitRequest\x12!\n" +
	"\amessage\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessage\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12%\n" +
	"\ttree_hash\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\btreeHash\x122\n" +
	"\rparent_hashes\x18\x04 \x03(\tB\r\xbaH\n" +
	"\x92\x01\a\"\x05r\x03\x98\x01@R\fparentHashes\x12\x1f\n" +
	"\vbranch_name\x18\x05 \x01(\tR\n" +
	"branchName\";\n" +
	"\x0eCommitResponse\x12)\n" +
	"\vcommit_hash\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\n" +
	"commitHash2\xfb\x01\n" +
	"\vDataService\x12P\n" +
	"\tCheckFile\x12 .tensorvault.v1.CheckFileRequest\x1a!.tensorvault.v1.CheckFileResponse\x12I\n" +
	"\x06Upload\x12\x1d.tensorvault.v1.UploadRequest\x1a\x1e.tensorvault.v1.UploadResponse(\x01\x12O\n" +
	"\bDownload\x12\x1f.tensorvault.v1.DownloadRequest\x1a .tensorvault.v1.DownloadResponse0\x012\xa2\x01\n" +
	"\vMetaService\x12J\n" +
	"\aGetHead\x12\x1e.tensorvault.v1.GetHeadRequest\x1a\x1f.tensorvault.v1.GetHeadResponse\x12G\n" +
	"\x06Commit\x12\x1d.tensorvault.v1.CommitRequest\x1a\x1e.tensorvault.v1.CommitResponseB\x1eZ\x1ctensorvault/pkg/api/tvrpc/v1b\x06proto3"

var (
	file_tensorvault_v1_tensorvault_proto_rawDescOnce sync.Once
	file_tensorvault_v1_tensorvault_proto_rawDescData []byte
)

func file_tensorvault_v1_tensorvault_proto_rawDescGZIP() []byte {
	file_tensorvault_v1_tensorvault_proto_rawDescOnce.Do(func() {
		file_tensorvault_v1_tensorvault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tensorvault_v1_tensorvault_proto_rawDesc), len(file_tensorvault_v1_tensorvault_proto_rawDesc)))
	})
	return file_tensorvault_v1_tensorvault_proto_rawDescData
}

var file_tensorvault_v1_tensorvault_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tensorvault_v1_tensorvault_proto_goTypes = []any{
	(*CheckFileRequest)(nil),  // 0: tensorvault.v1.CheckFileRequest
	(*CheckFileResponse)(nil), // 1: tensorvault.v1.CheckFileResponse
	(*UploadRequest)(nil),     // 2: tensorvault.v1.UploadRequest
	(*FileMeta)(nil),          // 3: tensorvault.v1.FileMeta
	(*UploadResponse)(nil),    // 4: tensorvault.v1.UploadResponse
	(*DownloadRequest)(nil),   // 5: tensorvault.v1.DownloadRequest
	(*DownloadResponse)(nil),  // 6: tensorvault.v1.DownloadResponse
	(*GetHeadRequest)(nil),    // 7: tensorvault.v1.GetHeadRequest
	(*GetHeadResponse)(nil),   // 8: tensorvault.v1.GetHeadResponse
	(*CommitRequest)(nil),     // 9: tensorvault.v1.CommitRequest
	(*CommitResponse)(nil),    // 10: tensorvault.v1.CommitResponse
}
var file_tensorvault_v1_tensorvault_proto_depIdxs = []int32{
	3,  // 0: tensorvault.v1.UploadRequest.meta:type_name -> tensorvault.v1.FileMeta
	0,  // 1: tensorvault.v1.DataService.CheckFile:input_type -> tensorvault.v1.CheckFileRequest
	2,  // 2: tensorvault.v1.DataService.Upload:input_type -> tensorvault.v1.UploadRequest
	5,  // 3: tensorvault.v1.DataService.Download:input_type -> tensorvault.v1.DownloadRequest
	7,  // 4: tensorvault.v1.MetaService.GetHead:input_type -> tensorvault.v1.GetHeadRequest
	9,  // 5: tensorvault.v1.MetaService.Commit:input_type -> tensorvault.v1.CommitRequest
	1,  // 6: tensorvault.v1.DataService.CheckFile:output_type -> tensorvault.v1.CheckFileResponse
	4,  // 7: tensorvault.v1.DataService.Upload:output_type -> tensorvault.v1.UploadResponse
	6,  // 8: tensorvault.v1.DataService.Download:output_type -> tensorvault.v1.DownloadResponse
	8,  // 9: tensorvault.v1.MetaService.GetHead:output_type -> tensorvault.v1.GetHeadResponse
	10, // 10: tensorvault.v1.MetaService.Commit:output_type -> tensorvault.v1.CommitResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_tensorvault_v1_tensorvault_proto_init() }
func file_tensorvault_v1_tensorvault_proto_init() {
	if File_tensorvault_v1_tensorvault_proto != nil {
		return
	}
	file_tensorvault_v1_tensorvault_proto_msgTypes[1].OneofWrappers = []any{}
	file_tensorvault_v1_tensorvault_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadRequest_Meta)(nil),
		(*UploadRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tensorvault_v1_tensorvault_proto_rawDesc), len(file_tensorvault_v1_tensorvault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tensorvault_v1_tensorvault_proto_goTypes,
		DependencyIndexes: file_tensorvault_v1_tensorvault_proto_depIdxs,
		MessageInfos:      file_tensorvault_v1_tensorvault_proto_msgTypes,
	}.Build()
	File_tensorvault_v1_tensorvault_proto = out.File
	file_tensorvault_v1_tensorvault_proto_goTypes = nil
	file_tensorvault_v1_tensorvault_proto_depIdxs = nil
}
